Fix #19: UI crash when chain is not synchronized before NeoCoin claim
neo-project/neo-gui pull request #39
Opened 2017-08-15 15:47 UTC by danielcrenna

Filter out any coin references we can't find in local chain, since CalculateBonus is more strict and assumes a complete height.

2017-08-15 15:56 UTC, erikzhang requested changes

2017-08-15 15:56 UTC, erikzhang commented on README.md
> +then copy `libleveldb.dll` to the working directory (i.e. /bin/Debug, /bin/Release)
Only need to build leveldb for Windows.
For linux, you can install it easily:
```
yum install leveldb-devel
```

2017-08-15 15:56 UTC, erikzhang commented on neo-gui.sln
> +VisualStudioVersion = 15.0.26730.3
Please don't change .sln file.

2017-08-15 16:03 UTC, danielcrenna commented on neo-gui.sln
> +VisualStudioVersion = 15.0.26730.3
sorry, reverted

2017-08-15 16:03 UTC, danielcrenna commented on README.md
> +then copy `libleveldb.dll` to the working directory (i.e. /bin/Debug, /bin/Release)
added to README

2017-08-16 07:05 UTC, erikzhang approved these changes

2017-08-16 07:06 UTC, merged